### ISSUE TITLE
let me know if you need help regarding the VBB API

### ISSUE THREAD

**Issue by derhuerst** [docterd/VBBNow#1]
shameless plug: I run [`vbb.transport.rest`](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md#berlin--brandenburg-public-transport-api), an unofficial API that wraps around the VBB API to make it [more usable](https://github.com/derhuerst/vbb-rest/blob/4332462b8a78092c8ec60388888d2a2793d86c6d/docs/why.md).

**Comment by obrhoff** [comment]
Hi, thanks for pointing that out but please write me a mail instead of opening issues.

**Comment by derhuerst** [comment]
I assumed that you like to keep open-source-related stuff on GitHub, just like other maintainers do. 😉 Well, I'm not going to bother any more.
